import yaml
import datetime
import re
from typing import List, Dict, Any
from core.parser import Node

# Region categorization mapping
REGIONS = {
    'HK': ['香港', 'HK', 'Hong Kong', '🇭🇰'],
    'TW': ['台湾', 'TW', 'Taiwan', '🇹🇼'],
    'JP': ['日本', 'JP', 'Japan', '🇯🇵'],
    'US': ['美国', 'US', 'United States', '🇺🇸'],
    'SG': ['新加坡', 'SG', 'Singapore', '🇸🇬'],
    'KR': ['韩国', 'KR', 'Korea', '🇰🇷'],
    'DE': ['德国', 'DE', 'Germany', '🇩🇪'],
    'GB': ['英国', 'GB', 'UK', 'United Kingdom', '🇬🇧'],
    'FR': ['法国', 'FR', 'France', '🇫🇷'],
    'RU': ['俄罗斯', 'RU', 'Russia', '🇷🇺'],
}

REGION_NAMES = {
    'HK': '🇭🇰 香港',
    'TW': '🇹🇼 台湾',
    'JP': '🇯🇵 日本',
    'US': '🇺🇸 美国',
    'SG': '🇸🇬 新加坡',
    'KR': '🇰🇷 韩国',
    'DE': '🇩🇪 德国',
    'GB': '🇬🇧 英国',
    'FR': '🇫🇷 法国',
    'RU': '🇷🇺 俄罗斯',
}

class Generator:
    def __init__(self, template_path: str):
        with open(template_path, 'r', encoding='utf-8') as f:
            self.template = yaml.safe_load(f)

    def generate(self, nodes: List[Node], output_path: str, source_count: int = 0, raw_count: int = 0, elapsed_time: float = 0):
        config = self.template.copy()
        clash_proxies = [node.to_clash() for node in nodes]
        node_names = [node.name for node in nodes] # Use .name from Node object
        
        config['proxies'] = clash_proxies
        
        # 1. Categorize nodes by region
        region_nodes: Dict[str, List[str]] = {key: [] for key in REGIONS}
        others: List[str] = []
        
        for name in node_names:
            found = False
            for key, keywords in REGIONS.items():
                for kw in keywords:
                    if kw in name or kw.lower() in name.lower():
                        region_nodes[key].append(name)
                        found = True
                        break
                if found: break
            if not found:
                others.append(name)

        # 2. Create Dynamic Region Groups
        dynamic_groups = []
        region_list_for_menu = []
        
        # Helper for common params
        test_url = "http://www.google.com/generate_204"
        test_interval = 300
        test_tolerance = 20

        for key, nodes_in_region in region_nodes.items():
            if not nodes_in_region:
                continue
            
            group_name = REGION_NAMES[key] # e.g. "🇯🇵 日本"
            auto_name = f"⚡ 自动选择 | {group_name}"
            
            # Regional Auto Group (Hidden)
            auto_group = {
                'name': auto_name, 'type': 'url-test', 'url': test_url,
                'interval': test_interval, 'tolerance': test_tolerance,
                'hidden': True, 'proxies': nodes_in_region
            }
            
            # Regional Select Group
            select_group = {
                'name': group_name, 'type': 'select',
                'proxies': [auto_name] + nodes_in_region
            }
            
            dynamic_groups.append(auto_group)
            dynamic_groups.append(select_group)
            region_list_for_menu.append(group_name)

        # Handle Others
        if others:
            others_group_name = '🌍 其他地区'
            others_auto_name = f"⚡ 自动选择 | {others_group_name}"
            dynamic_groups.append({
                'name': others_auto_name, 'type': 'url-test', 'url': test_url,
                'interval': test_interval, 'tolerance': test_tolerance,
                'hidden': True, 'proxies': others
            })
            dynamic_groups.append({
                'name': others_group_name, 'type': 'select',
                'proxies': [others_auto_name] + others
            })
            region_list_for_menu.append(others_group_name)

        # 3. Fill Template Groups
        template_groups = config.get('proxy-groups', [])
        for g in template_groups:
            if g['name'] == '🗺️ 选择地区':
                g['proxies'] = region_list_for_menu
            elif g['name'] in ('♻️ 自动选择', '🔰 延迟最低', '✅ 手动选择'):
                g['proxies'] = node_names
        
        # Add the dynamic regional groups
        config['proxy-groups'] = template_groups + dynamic_groups

        # 4. Save YAML
        with open(output_path, 'w', encoding='utf-8') as f:
            now_str = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            f.write(f"# Generated by MetaFetch\n")
            f.write(f"# Updated at: {now_str}\n")
            yaml.dump(config, f, allow_unicode=True, default_flow_style=False, sort_keys=False)
        
        # 5. Update README.md Statistics
        self.update_readme(len(nodes), region_nodes, others, now_str, source_count, raw_count, elapsed_time)
        print(f"Successfully generated {len(nodes)} nodes with region selection to {output_path}")

    def update_readme(self, total_nodes: int, region_nodes: Dict[str, List[str]], others: List[str], timestamp: str, source_count: int, raw_count: int, elapsed_time: float):
        readme_path = "README.md"
        import os
        if not os.path.exists(readme_path):
            return

        with open(readme_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # 1. Update Badges
        badge_content = f"![Update](https://img.shields.io/badge/Updated-{timestamp.replace(' ', '--').replace(':', '%3A')}-green.svg)\n"
        badge_content += f"![Nodes](https://img.shields.io/badge/Valid_Nodes-{total_nodes}-orange.svg)\n"
        badge_content += f"![Sources](https://img.shields.io/badge/Active_Sources-{source_count}-blue.svg)"
        
        import re
        content = re.sub(r'<!-- STATS_BADGE_START -->.*?<!-- STATS_BADGE_END -->', 
                         f'<!-- STATS_BADGE_START -->\n{badge_content}\n<!-- STATS_BADGE_END -->', 
                         content, flags=re.DOTALL)

        # 2. Update Table (Horizontal Layout)
        header_row = ["地区分布"]
        value_row = ["**数量**"]
        
        for key, name in REGION_NAMES.items():
            count = len(region_nodes.get(key, []))
            if count > 0:
                header_row.append(name) # 保留完整的名称和 Emoji
                value_row.append(str(count))
        
        if others:
            header_row.append("🌍 其他")
            value_row.append(str(len(others)))
            
        header_row.append("**总计**")
        value_row.append(f"**{total_nodes}**")
        
        # Build Markdown Table
        table_header = "| " + " | ".join(header_row) + " |"
        table_sep = "| :---: " + "| :---: " * (len(header_row) - 1) + "|"
        table_values = "| " + " | ".join(value_row) + " |"
        
        table_markdown = f"{table_header}\n{table_sep}\n{table_values}"
        
        # Stats summary
        stats_summary = f"""> 更新时间：`{timestamp}`
> 运行分析：从 `{source_count}` 个活跃源中抓取 `{raw_count}` 个节点，耗时 `{elapsed_time:.2f}s`。去重后保留 `{total_nodes}` 个有效节点。"""

        table_new_content = f"""{stats_summary}\n\n{table_markdown}"""
        
        content = re.sub(r'<!-- STATS_TABLE_START -->.*?<!-- STATS_TABLE_END -->', 
                         f'<!-- STATS_TABLE_START -->\n{table_new_content}\n<!-- STATS_TABLE_END -->', 
                         content, flags=re.DOTALL)

        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(content)
