REGIONS_DB = {
    'HK': {'name': '香港', 'emoji': '🇭🇰', 'keywords': ['HK', 'Hong Kong', 'HKG']},
    'TW': {'name': '台湾', 'emoji': '🇹🇼', 'keywords': ['TW', 'Taiwan', 'TWN']},
    'JP': {'name': '日本', 'emoji': '🇯🇵', 'keywords': ['JP', 'Japan', 'JPN']},
    'US': {'name': '美国', 'emoji': '🇺🇸', 'keywords': ['US', 'United States', 'USA']},
    'SG': {'name': '新加坡', 'emoji': '🇸🇬', 'keywords': ['SG', 'Singapore', 'SGP']},
    'KR': {'name': '韩国', 'emoji': '🇰🇷', 'keywords': ['KR', 'Korea', 'KOR']},
    'DE': {'name': '德国', 'emoji': '🇩🇪', 'keywords': ['DE', 'Germany', 'DEU']},
    'GB': {'name': '英国', 'emoji': '🇬🇧', 'keywords': ['GB', 'UK', 'United Kingdom']},
    'FR': {'name': '法国', 'emoji': '🇫🇷', 'keywords': ['FR', 'France', 'FRA']},
    'RU': {'name': '俄罗斯', 'emoji': '🇷🇺', 'keywords': ['RU', 'Russia', 'RUS']},
    'CA': {'name': '加拿大', 'emoji': '🇨🇦', 'keywords': ['CA', 'Canada', 'CAN']},
    'VN': {'name': '越南', 'emoji': '🇻🇳', 'keywords': ['VN', 'Vietnam', 'VNM']},
    'NL': {'name': '荷兰', 'emoji': '🇳🇱', 'keywords': ['NL', 'Netherlands', 'NLD']},
    'CH': {'name': '瑞士', 'emoji': '🇨🇭', 'keywords': ['CH', 'Switzerland', 'CHE']},
    'IN': {'name': '印度', 'emoji': '🇮🇳', 'keywords': ['IN', 'India', 'IND']},
    'TR': {'name': '土耳其', 'emoji': '🇹🇷', 'keywords': ['TR', 'Turkey', 'TUR']},
    'AU': {'name': '澳大利亚', 'emoji': '🇦🇺', 'keywords': ['AU', 'Australia', 'AUS']},
    'TH': {'name': '泰国', 'emoji': '🇹🇭', 'keywords': ['TH', 'Thailand']},
    'PH': {'name': '菲律宾', 'emoji': '🇵🇭', 'keywords': ['PH', 'Philippines']},
    'MY': {'name': '马来西亚', 'emoji': '🇲🇾', 'keywords': ['MY', 'Malaysia']},
    'ID': {'name': '印尼', 'emoji': '🇮🇩', 'keywords': ['ID', 'Indonesia']},
    'BR': {'name': '巴西', 'emoji': '🇧🇷', 'keywords': ['BR', 'Brazil']},
    'AR': {'name': '阿根廷', 'emoji': '🇦🇷', 'keywords': ['AR', 'Argentina']},
    'MX': {'name': '墨西哥', 'emoji': '🇲🇽', 'keywords': ['MX', 'Mexico']},
    'IT': {'name': '意大利', 'emoji': '🇮🇹', 'keywords': ['IT', 'Italy']},
    'ES': {'name': '西班牙', 'emoji': '🇪🇸', 'keywords': ['ES', 'Spain']},
    'CN': {'name': '中国', 'emoji': '🇨🇳', 'keywords': ['CN', 'China', 'CHN']},
    'RO': {'name': '罗马尼亚', 'emoji': '🇷🇴', 'keywords': ['RO', 'Romania', 'ROU']},
    'FI': {'name': '芬兰', 'emoji': '🇫🇮', 'keywords': ['FI', 'Finland', 'FIN']},
}
